insert into STATES(abbv, name, capital) values ('AL','Alabama','Montgomery');
insert into STATES(abbv, name, capital) values ('AK','Alaska','Juneau');
insert into STATES(abbv, name, capital) values ('AZ','Arizona','Phoenix');
insert into STATES(abbv, name, capital) values ('AR','Arkansas','Little Rock');
insert into STATES(abbv, name, capital) values ('CA','California','Sacramento');
insert into STATES(abbv, name, capital) values ('CO','Colorado','Denver');
insert into STATES(abbv, name, capital) values ('CT','Connecticut','Hartford');
insert into STATES(abbv, name, capital) values ('DE','Delaware','Dover');
insert into STATES(abbv, name, capital) values ('FL','Florida','Tallahassee');
insert into STATES(abbv, name, capital) values ('GA','Georgia','Atlanta');
insert into STATES(abbv, name, capital) values ('HI','Hawaii','Honolulu');
insert into STATES(abbv, name, capital) values ('ID','Idaho','Boise');
insert into STATES(abbv, name, capital) values ('IL','Illinois','Springfield');
insert into STATES(abbv, name, capital) values ('IN','Indiana','Indianapolis');
insert into STATES(abbv, name, capital) values ('IA','Iowa','Des Moines');
insert into STATES(abbv, name, capital) values ('KS','Kansas','Topeka');
insert into STATES(abbv, name, capital) values ('KY','Kentucky','Frankfort');
insert into STATES(abbv, name, capital) values ('LA','Louisiana','Baton Rouge');
insert into STATES(abbv, name, capital) values ('ME','Maine','Augusta');
insert into STATES(abbv, name, capital) values ('MD','Maryland','Annapolis');
insert into STATES(abbv, name, capital) values ('MA','Massachusetts','Boston');
insert into STATES(abbv, name, capital) values ('MI','Michigan','Lansing');
insert into STATES(abbv, name, capital) values ('MN','Minnesota','Saint Paul');
insert into STATES(abbv, name, capital) values ('MS','Mississippi','Jackson');
insert into STATES(abbv, name, capital) values ('MO','Missouri','Jefferson City');
insert into STATES(abbv, name, capital) values ('MT','Montana','Helena');
insert into STATES(abbv, name, capital) values ('NE','Nebraska','Lincoln');
insert into STATES(abbv, name, capital) values ('NV','Nevada','Carson City');
insert into STATES(abbv, name, capital) values ('NH','New Hampshire','Concord');
insert into STATES(abbv, name, capital) values ('NJ','New Jersey','Trenton');
insert into STATES(abbv, name, capital) values ('NM','New Mexico','Santa Fe');
insert into STATES(abbv, name, capital) values ('NY','New York','Albany');
insert into STATES(abbv, name, capital) values ('NC','North Carolina','Raleigh');
insert into STATES(abbv, name, capital) values ('ND','North Dakota','Bismarck');
insert into STATES(abbv, name, capital) values ('OH','Ohio','Columbus');
insert into STATES(abbv, name, capital) values ('OK','Oklahoma','Oklahoma City');
insert into STATES(abbv, name, capital) values ('OR','Oregon','Salem');
insert into STATES(abbv, name, capital) values ('PA','Pennsylvania','Harrisburg');
insert into STATES(abbv, name, capital) values ('RI','Rhode Island','Providence');
insert into STATES(abbv, name, capital) values ('SC','South Carolina','Columbia');
insert into STATES(abbv, name, capital) values ('SD','South Dakota','Pierre');
insert into STATES(abbv, name, capital) values ('TN','Tennessee','Nashville');
insert into STATES(abbv, name, capital) values ('TX','Texas','Austin');
insert into STATES(abbv, name, capital) values ('UT','Utah','Salt Lake City');
insert into STATES(abbv, name, capital) values ('VT','Vermont','Montpelier');
insert into STATES(abbv, name, capital) values ('VA','Virginia','Richmond');
insert into STATES(abbv, name, capital) values ('WA','Washington','Olympia');
insert into STATES(abbv, name, capital) values ('WV','West Virginia','Charleston');
insert into STATES(abbv, name, capital) values ('WI','Wisconsin','Madison');
insert into STATES(abbv, name, capital) values ('WY','Wyoming','Cheyenne');
